### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by RubenGuedes** [RubenGuedes/PI_2018#1]
- [x] sublist (quase a terminar)
- [x] simple linked list (submeter)
- [x] markdown (quase a terminar)
